config/routes.rb
Myrorhub::Application.routes.draw do
  get "aboutme/index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users do
	resources :articles
  end
  
  resources :articles do 
		resources :comments	
	end
	
  resources :comments	do
	collection do
		get 'approve'
    end
  end
  
  root :to => "articles#index"
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :description, :title
    belongs_to :user
    has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  attr_accessible :description, :name, :c_approval_status
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable 
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid, :token, :name, :image
  # attr_accessible :title, :body
   #Association
  has_many :articles
  #thirdparty authentication
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  user = User.where(:provider => auth.provider, :uid => auth.uid).first
  unless user
    user = User.create(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20],
                         image:auth.info.image
                         )
  end
  user
end
 def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
  data = access_token.info
	  if user = User.where(:email => data["email"]).first
		user
	  else
		User.create!(:email => data["email"], :password => Devise.friendly_token[0,20], :name => data["name"])
	  end
  end
end

app/controllers/aboutme_controller.rb
class AboutmeController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
   require 'will_paginate/array' 
  def index
	if user_signed_in?
	 	@article = Article.find(:all, :conditions => {:user_id => current_user.id}).paginate(:page => params[:page], :per_page => 7)	
	else
		@articles = Article.find(:all).paginate(:page => params[:page], :per_page => 7)
	end
  end
  # GET /articles/1
  # GET /articles/1.json
  def show
   @user = User.find(params[:user_id])
   
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
   @user = User.find(params[:user_id])
   @userid = @user._id
    
  end

  # GET /articles/1/edit
  def edit
    @user = User.find(params[:user_id])
    @article = @user.articles.find(params[:id])
  end

  # POST /articles
  # POST /articles.json

  def create
	 @user = User.find(params[:user_id])
 
     @article = @user.articles.create!(params[:article])
	 
	 redirect_to root_path
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
     @user = User.find(params[:user_id])
 
     @article = @user.articles.update(params[:id])
	 
	 redirect_to root_path

  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  require 'will_paginate/array' 
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @article = Article.find(params[:article_id])
    @comment = Comment.find(:all, :conditions => {:article_id => @article.id })
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
		@article = Article.find(params[:article_id])
		
        @comment = Comment.find(:all, :conditions => {:article_id => @article.id }).paginate(:page => params[:page], :per_page => 5)
       
       @article_user_email = User.find(:all, :select => :email, :conditions => {:id=> @article.user_id}).first
       @email = @article_user_email.email
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
      
      @article = Article.find(params[:article_id])
      @article_user_email = User.find(:all,  :conditions => {:id=> @article.user_id}).first
      @email = @article_user_email.email
   if user_signed_in?   
	if current_user.email == @email
		@comment = @article.comments.create!(params[:comment])
		@comment.update_attribute(:c_approval_status,1)
		 redirect_to  new_article_comment_path(@article.id )
	else

    end  
    else
		@comment = @article.comments.create!(params[:comment])
		if @comment.save
			@mymail = @email
			UserMailer.comment_approval(@mymail,@comment).deliver
		end
      redirect_to new_article_comment_path(@article.id )
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

 def approve

 @comment = Comment.find(params[:cid])
 @articleid = Article.find(@comment.article_id)
 @approve = params[:approve]
 @comment.update_attributes(:c_approval_status => params[:approve])
 redirect_to  new_article_comment_path( @articleid )
 end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
 def google_oauth2
	    # You need to implement the method below in your model (e.g. app/models/user.rb)
	    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)
	    if @user.persisted?
	      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
	      sign_in_and_redirect @user, :event => :authentication
	    else
	      session["devise.google_data"] = request.env["omniauth.auth"]
	      redirect_to new_user_registration_url
	    end
	end
	def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/aboutme_helper.rb
module AboutmeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/aboutme/index.html.erb
<div id ="mainpagediv">
	<table>
	<tr>
		<td>
			<b>Name: </b><%= current_user.name %>
		</td>
		<td>
			<%if current_user.provider == "facebook"%>
				<%= image_tag current_user.image %>
			<%end%>	
		</td>
	</tr>

	<tr>
		<td>
			<b>Number of time i logins: </b>
		</td>
		<td>
			<%= User.find(:all, :select => :sign_in_count,  :conditions => {:id => current_user.id}).map(&:sign_in_count).first%><b>
		</td>
		<td></td>
	</tr>
	</table>
</div>
<style>
#mainpagediv {
 border: 1px solid #999999;
    border-radius: 8px 8px 8px 8px;
    box-shadow: 0 -1px 24px #000000;
    float: left;
    font-size: 95%;
    left: 22%;
    margin: 0;
    overflow: auto;
    padding: 10px;
    position: relative;
    width: 46%;
}
</style>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% if user_signed_in? %>
	<div id= "mainpagediv">
		All Articles
		<table border = 1>
			<tr>
				<th>
					Title
				</th>
				<th>
					Description
				</th>
				<th>
					Show
				</th>
			</tr>
				<%@article.each do |all|%>
				<tr>
					<td>
						<%= all.title%>
					 </td>
					 <td>
						<%= all.description%>
					 </td>
					 <td>
						<%= link_to "Read ..", new_article_comment_path( all.id )%>
					 </td>
				 </tr>
				<%end%>
		</table>
		<br />
		</div><br /><br />
		<%= will_paginate @article %><br>
		<%= link_to 'New Article',  new_user_article_path(current_user.id), :id => "buttonstyle", %>
<%else%>
		<h2>All Articles<h2>
		<div id= "mainpagediv">
		<table border = 1>
		<tr>
			<th>
				Title
			</th>
			<th>
				Description
			</th>
			<th>
				Make comment
			</th>
		</tr>
			<%@articles.each do |all|%>
			<tr>
				<td>
					<%= all.title%>
				 </td>
				 <td>
					<%= all.description%>
				 </td>
				  <td>
					<%= link_to "comment",   new_article_comment_path(all.id)%>
				 </td>
			 </tr>
			<%end%>	
		</table>
		</div>
	<br>	<%= will_paginate @article %>
<%end%>
<style>
#mainpagediv{
	border: 1px solid #999999;
	border-radius: 8px 8px 8px 8px;
    font-size: 95%;
    margin: 0;
    overflow: auto;
    padding: 10px;
    position: relative;
    -moz-box-shadow: 0px -1px 24px #000000;
    -webkit-box-shadow: 0px -1px 24px #000000;
    box-shadow: 0px -1px 24px #000000;
   }
   #buttonstyle
{
		-moz-user-select: none;
		border: medium none;
		border-radius: 5px 5px 5px 5px;
		box-shadow: 0 1px 2px rgba(0, 0, 0, 0.5);
		color: #FFFFFF !important;
		cursor: pointer;
		display: inline-block;
		padding: 5px 10px !important;
		text-shadow: 0 -1px 1px rgba(0, 0, 0, 0.25), -2px 0 1px rgba(0, 0, 0, 0.25);
		background-color: #015EA9;
		text-decoration:none;
}
   </style>

app/views/articles/new.html.erb
<div id ="new_look">
<%= form_for [@user, @user.articles.build] do |f| %>
  <table>
  <tr>
    <td><%= f.label "Title" %></td>
    <td><%= f.text_field :title %></td>
   </tr>
  <tr>
    <td><%= f.label :description %></td>
    <td><%= f.text_area :description %></td>
   </tr>
 <tr>
    <td><%= f.submit :id => "buttonstyle"%></td>
  </tr>
    </table>
<% end %>
</div >
<style>
	#new_look{background: #F5FCFC;  border-radius: 5px 5px 5px 5px;
    margin-left: 50px;
    max-width: 65%;}
    #tdleft{float: right; top: 9px; position: relative;}
    textarea {
    resize: none;
    cols: 20;
    rows: 40;
    width: 462px; height: 214px;
    }
     #buttonstyle
{
		-moz-user-select: none;
		border: medium none;
		border-radius: 5px 5px 5px 5px;
		box-shadow: 0 1px 2px rgba(0, 0, 0, 0.5);
		color: #FFFFFF !important;
		cursor: pointer;
		display: inline-block;
		padding: 5px 10px !important;
		text-shadow: 0 -1px 1px rgba(0, 0, 0, 0.25), -2px 0 1px rgba(0, 0, 0, 0.25);
		background-color: #015EA9;
		text-decoration:none;
}
</style>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Description:</b>
  <%= @article.description %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_form.html.erb
<div id ="new_look">
<%= form_for [@article, @article.comments.build]  do |f| %>
  <table>
  <tr>
    <td><%= f.label "Commenter Name" %></td>
    <td><%= f.text_field :name %></td>
  </tr>
  <tr>
    <td><%= f.label "Description" %></td>
    <td><%= f.text_area :description %></td>
  </tr>
  <tr>
    <td><%= f.submit %></td>
  </tr>
  </table>
<% end %>
</div>
<style>
	#new_look{background: #F5FCFC;  border-radius: 5px 5px 5px 5px;
    margin-left: 50px;
    max-width: 65%;}
    #tdleft{float: right; top: 9px; position: relative;}
    textarea {
    resize: none;
    cols: 20;
    rows: 40;
    width: 462px; height: 214px;
    }
</style>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>C title</th>
    <th>C description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.c_title %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>Article</h1>
Title : <%=@article.title%><br>
Description : <%=@article.description%>
<div id='fb-root'></div>
	<script src='http://connect.facebook.net/en_US/all.js'></script>
	<p><a onclick='postToFeed(); return false;'><span id = "sharebutton"></span></a></p>

	<script> 
	  FB.init({appId: "111715892321751", status: true, cookie: true});

	  function postToFeed() {
	 
		// calling the API ...
		var obj = {
		  method: 'feed',
		  link: 'http://localhost:3000/articles/<%=@article.id%>/comments/new/',
		  picture: 'http://fbrell.com/f8.jpg',
		  caption: '<%=@article.title%>',
		  description: '<%=@article.description%>'
		};

		function callback(response) {
		  document.getElementById('msg').innerHTML = "Post ID: " + response['post_id'];
		}

		FB.ui(obj, callback);
	  }
	
	</script>
	<div class="fb-like" data-send="true" data-width="450" data-show-faces="true" data-font="verdana"></div>
	<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=111715892321751";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>		
<br>
<hr>
<h1>All Comments </h1>
<div class="background_comment">
	<% if user_signed_in? %>
		<%if current_user.email == @email%>
			<table>
				<% @comment.each do |allcomments|%>
						<tr >
							<td  width="60%" id = "inside_comment" style ="border-bottom: 2px solid #000000;">
								
									Commenter Name: <%=allcomments.name%><br>
									Comment Description: <%=allcomments.description%>
								
							</td>
							<td width ="40%" style ="border-bottom: 2px solid #000000; text-align: right;">
								
									 <%= time_ago_in_words(allcomments.created_at)%>
									
													
						</td>
						</tr >
				<%end%>
			</table>
		<%else%>
			<% @comment.each do |allcomments|%>
				<% if allcomments.c_approval_status == "1" %>
					Commenter Name: <%=allcomments.name%><br>
					Comment Description: <%=allcomments.description%><br>
				<% end %>
			<%end%>
		<%end%>
	<%else%>
			<% @comment.each do |allcomment|%>
				<% if allcomment.c_approval_status.to_i == 1%>
					Commenter Name: <%=allcomment.name%><br>
					Comment Description: <%=allcomment.description%><br>
				<% end %>
			<%end%>
		<%end%>
</div>
<%= will_paginate @comment %>
	<%= link_to "Show all Articles", articles_path%>
<h2>Make Comment</h2>

<%= render 'form' %>
<style>
.background_comment
{
		background-color: #EDEFF4;
		border-radius: 5px 5px 5px 5px;
		max-width: 60%;
}
#inside_comment
{
#max-width: 77%;
    padding: 8px 21px 1px;
}
#datelocation{background-color: red;}
#test{float: right;padding: 23px 20px 1px;}
#sharebutton{background-image: url("/assets/fbshare.png");
    background-position: 0 center;
    background-size: 76px auto;
    border-radius: 5px 5px 5px 5px;
    float: right;
    padding: 25px 38px 1px;
    position: relative;
    right: 30px;
    top: -15px;}
</style>

app/views/comments/show.html.erb
Title: <%=@article.title%>
Description <%= @article.description%>
<br>
<hr>
<% @comment.each do |allcomments|%>
<% if allcomments.c_approval_status == "1" %>
	Comment Title: <%=allcomments.c_name%><br>
	Comment Description: 	<%=allcomments.c_description%><br><hr>
					
<% end %>
<%end%>
<%= link_to "comment again",  new_article_comment_path(@article.id)%>
<%= link_to "all articles", user_articles_path(@article.id)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myrorhub</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 
</head>

 <script >
		ddsmoothmenu.init({
			mainmenuid: "smoothmenu1", //menu DIV id
			orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
			classname: 'ddsmoothmenu', //class added to menu's outer DIV
			//customtheme: ["#1c5a80", "#18374a"],
			contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
		})

		ddsmoothmenu.init({
			mainmenuid: "smoothmenu2", //Menu DIV id
			orientation: 'v', //Horizontal or vertical menu: Set to "h" or "v"
			classname: 'ddsmoothmenu-v', //class added to menu's outer DIV
			//customtheme: ["#804000", "#482400"],
			contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
		})
</script>
<body>
	
<div class="navigation">
		  <% if user_signed_in? %>
			<span class = "textcolor"> Signed in as <%= current_user.email %> </span>
		   <%= button_to "", destroy_user_session_path, :method => :delete, :id => "signout" %>
		    <div class="menubar">
				<div  id="smoothmenu1" class="ddsmoothmenu">
					<ul>
						<li id="article"><a href="/articles">Dashboard</a></li>
						<li id="aboutme"><a href="/aboutme/index">About Me</a></li>
					</ul>
					
				</div>
			</div>
		  <% else %>
			<%#= button_to "", new_user_registration_path, :id => "signup" %><%= button_to "", new_user_session_path, :id => "signin" %>
			<%= button_to "", user_omniauth_authorize_path(:google_oauth2) , :id => "googlesignin"%>  <%= button_to "", user_omniauth_authorize_path(:facebook) , :id => "facebooksignin"%>
		  <% end %>
		</div>
		<div class="wrapper">
			<%= yield %>
		</div>
		<footer>
			<div id = "footer">
				venkat corporation
			</div>
		</footer>
</body>
</html>
<style>
	#footer{
	background-image: url("/assets/bg-footer.jpg");
    border-top: 1px solid #BBBBBB;
    clear: both;
    color: #AAAAAA;
    font-size: 0.9em;
    padding: 5px;
    text-align: center;

}
	.textcolor{color: #FFFFFF;
    position: relative;
    top: 11px;}
	.navigation {
    background-image: url("/assets/header.png");
    height: 51px;
    margin: -7px -7px 2%;
}
#signout{  background-image: url("/assets/run.png");
    background-position: -2px -2px;
    background-size: 113% auto;
    float: right;
    height: 33px;
    position: relative;
    right: 2%;
    top: -10px;
    width: 3%;}
#signup{    background-image: url("/assets/singup.png");
    background-position: -2px -2px;
    background-size: 29px auto;
    float: right;
    height: 30px;
    position: relative;
    right: 17%;
    top: 12px;
    width: 2%;}
#signin{     background-image: url("/assets/normaluser.png");
    background-position: -2px -2px;
    background-size: 113% auto;
    float: right;
    height: 33px;
    position: relative;
    right: 12%;
    top: 11px;
    width: 3%;}
#googlesignin{   background-image: url("/assets/google.png");
    background-position: -2px -2px;
    background-size: 113% auto;
    float: right;
    height: 33px;
    position: relative;
    right: 5%;
    top: 11px;
    width: 3%;}

#facebooksignin{  background-image: url("/assets/facebook.png");
    background-position: -2px -2px;
    background-size: 113% auto;
    float: right;
    height: 33px;
    position: relative;
    right: -2%;
    top: 11px;
    width: 3%;}
    .wrapper {
	height: auto;
    margin: 29px auto;
    min-height: 100%;
}
html, body {
height: 93%;
}
.menubar{   background: none repeat scroll 0 0 #FFFFFF;
    float: right;
    max-width: 15%;
    position: relative;
    right: 44%;
    top: -24%;
    }

	</style>